version: "3.8"
services:
  database:
    image: postgres:latest
    container_name: db
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    networks:
      - ft_transcendence

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend-dockerfile
    container_name: frontend
    ports:
      - '8080:8080'
    networks:
      - ft_transcendence

  backend:
    build:
      context: ./backend
      dockerfile: backend-dockerfile
    container_name: backend
    ports:
      - '3000:3000'
      - '4242:4242'
    depends_on:
      - database
    networks:
      - ft_transcendence
    env_file:
      - ./backend/.env

networks:
  ft_transcendence:
    driver: bridge

volumes:
  postgres_data: